name: planilla_android
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.6
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_getit: ^2.0.0
  logging: ^1.2.0
  path_provider: ^2.1.3
  top_snackbar_flutter: ^3.1.0
  file_picker: ^8.0.3
  csv: ^6.0.0
  universal_platform: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
