// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8BSQ6vmuvkvSpfRRZUGZcUjzkxDMI4iY',
    appId: '1:1010962985909:web:9e269a6ef87b1878161ffc',
    messagingSenderId: '1010962985909',
    projectId: 'planilla-pt2024',
    authDomain: 'planilla-pt2024.firebaseapp.com',
    storageBucket: 'planilla-pt2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gj6SuI95aWxVxH8zUB_t3PbQwR99hdo',
    appId: '1:1010962985909:android:6ef27db294f80835161ffc',
    messagingSenderId: '1010962985909',
    projectId: 'planilla-pt2024',
    storageBucket: 'planilla-pt2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnT-77GP2i0mQ-ZxWcFgNcs6nvfpyF9bQ',
    appId: '1:1010962985909:ios:b6334637ab893976161ffc',
    messagingSenderId: '1010962985909',
    projectId: 'planilla-pt2024',
    storageBucket: 'planilla-pt2024.appspot.com',
    iosBundleId: 'com.example.planillaAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnT-77GP2i0mQ-ZxWcFgNcs6nvfpyF9bQ',
    appId: '1:1010962985909:ios:b6334637ab893976161ffc',
    messagingSenderId: '1010962985909',
    projectId: 'planilla-pt2024',
    storageBucket: 'planilla-pt2024.appspot.com',
    iosBundleId: 'com.example.planillaAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8BSQ6vmuvkvSpfRRZUGZcUjzkxDMI4iY',
    appId: '1:1010962985909:web:d771aa88269f6bd4161ffc',
    messagingSenderId: '1010962985909',
    projectId: 'planilla-pt2024',
    authDomain: 'planilla-pt2024.firebaseapp.com',
    storageBucket: 'planilla-pt2024.appspot.com',
  );
}
